# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20160726_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='break_length_min',
            new_name='break_length',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='session_length_min',
            new_name='session_length',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
