# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20160729_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='owner',
            new_name='user',
        ),
    ]
